### ISSUE TITLE
Increase entities/tile entities limits by island level

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/addon-limits#1]
_From @tastybento on July 15, 2017 22:8_

_From @Poslovitch on March 29, 2017 18:34_

_From @Poslovitch on January 20, 2017 19:52_

https://www.spigotmc.org/threads/a-skyblock.30325/page-167#post-2176809

Add per-island-level limits for entities and tile entities.

_Copied from original issue: tastybento/askyblock#465_

_Copied from original issue: tastybento/ASkyBlock-Bugs-N-Features#34_

_Copied from original issue: BentoBoxWorld/bentobox#40_

**Comment by tastybento** [comment]
There's enough flexibility already.
