### ISSUE TITLE
Addon not working anymore

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/addon-limits#11]
**Description**
Before opening the server to the public the addon was working fine just for me but today I've realised IslandBlockCount folder is empty and it is not counting anything.
Any error on console, the only message at startup:

> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Loading default limits
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit HOPPER to 250
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit PISTON to 400
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit STICKY_PISTON to 400
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit OBSERVER to 800
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit REDSTONE_TORCH to 400
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit REDSTONE_WIRE to 3500
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit REPEATER to 350
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit DROPPER to 50
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit DISPENSER to 50
> [10:13:49] [Server thread/INFO]: [BentoBox] [Limits] Limit SPAWNER to 4
> [10:13:49] [Server thread/INFO]: [BentoBox] Enabling Limits...

**Server Information:**

[Please complete the following information:]
 - Database: yml
- Limits: 0.1.0

**Comment by tastybento** [comment]
Is this in your console above the Loading default limits line?

```
Limits will apply to BSkyBlock
Limits will apply to AcidIsland
```

If not, then check the top of your config.yml file for limits. It should look like this:

```
# Game Modes covered by limits
gamemodes:
- AcidIsland
- BSkyBlock
- CaveBock
```

Note that these are not world names. They are Game Modes, so they are the name of the addon. Share what you have.

**Comment by YellowZaki** [comment]
I hadn't that section in my config.yml. Added and now it is working :)
Thanks.

**Comment by tastybento** [comment]
Check that config looks like this too:
https://github.com/BentoBoxWorld/addon-limits/blob/master/src/main/resources/config.yml

I think it's because you were an early user and the config was updated, but it doesn't overwrite.
