### ISSUE TITLE
Unable to open a /bsbadmin limit GUI

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/addon-limits#18]
**Description**
I am not unable to open /bsbadmin limits GUI (nor /island limits) with new **Limits** snapshot.
Note: Entity limit works perfect. See an example below.

**Steps to reproduce the behavior:**
1. Have entity limits in configuration like me:
```
  CHICKEN: 10
  PIG: 10
  COW: 10
  DONKEY: 10
  HORSE: 10
  LLAMA: 10
  MULE: 10
  MUSHROOM_COW: 10
  ITEM_FRAME: 100
  REDSTONE_COMPARATOR: 100
  TURTLE: 30
  ZOMBIE: 40
  SKELETON: 40
  CREEPER: 40
  BAT: 5
  BEACON: 30
```
2. Try to spawn more than 10 Pigs (Entity limit works perfect) (Yellow arrows on screenshot)
3. Type **/bsbadmin limits** <player> or **/island limits** (Blue arrow on screenshot)
3. See: https://prntscr.com/nk9k7o (No limits set in this world)

**Expected behavior**
Open a nice looking GUI that I've seen earlier on my localhost test server.

**Server Information:**

 - Database being used: **mySQL**
 - OS: **Debian GNU/Linux 9**
 - Java Version: 
**Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)**
- BentoBox output: 
```
[12:47:55] [main/INFO]: [CHAT] Running PAPER 1.13.2.
[12:47:55] [main/INFO]: [CHAT] BentoBox version: 1.5.0-SNAPSHOT
[12:47:55] [main/INFO]: [CHAT] Loaded Game Worlds:
[12:47:55] [main/INFO]: [CHAT] skyblock (skyblock)
[12:47:55] [main/INFO]: [CHAT] Loaded Add-Ons
[12:47:55] [main/INFO]: [CHAT] Biomes 0.4.5-SNAPSHOT-#28
[12:47:55] [main/INFO]: [CHAT] BSkyBlock 1.4.2
[12:47:55] [main/INFO]: [CHAT] Challenges 0.7.0-SNAPSHOT-#163
[12:47:55] [main/INFO]: [CHAT] Level 1.4.0
[12:47:55] [main/INFO]: [CHAT] Limits 0.2.0-SNAPSHOT
[12:47:55] [main/INFO]: [CHAT] SerbCraftAddon 2.2
[12:47:55] [main/INFO]: [CHAT] WelcomeWarps 1.4.0
```

 - Other plugins? 
`[06:32:17 INFO]: Plugins (50): AnimatedNames*, AreaShop, ArmorStandTools, BentoBox, BungeeTabListPlus*, ChatControl, ChestCommands, ChestShop*, ClearLag*, CrateReloaded, EditableSign, Essentials, EssentialsChat*, EssentialsSpawn*, ExecuteEverywhere*, FastAsyncWorldEdit*, FeatherBoard*, HeadDatabase*, HolographicDisplays, HungerKeeperPlus*, IPWhitelist*, IslandBorder, LeaderHeads*, LibsDisguises, LuckPerms, MobManager*, Multiverse-Core*, MVdWPlaceholderAPI*, NickRemover*, NoSleepCMDs*, OpenInv*, PlayerHeads, PlayerPoints*, ProtocolLib*, PvPManager*, PvPManagerBossBar*, RedstoneClockDetector*, RPGHealthIndicator*, SilkSpawners, SkinsRestorer, Spartan, TradeMe, TrophyHeads*, UnbreakingAnvils*, Vault*, VoidGenerator, WorldEdit, WorldGuard, WorldGuardPistonFix*, Yamler*`

**Additional context**
Please note that I have successfully opened it on a fresh server (It was build #108), but not on our live one too. I don't know what can be the problem, our config seems to be alright too.

**Comment by tastybento** [comment]
Thanks, this is caused when there are no block limits in the config. It was left over from the older version which just handled block limits. Fixed now.
