### ISSUE TITLE
Mob spawner limits won't decrease after breaking it while using EpicSpawners Plugin.

### ISSUE THREAD

**Issue by variananora** [BentoBoxWorld/addon-limits#19]
**Description**
Mob spawner limits won't decrease after breaking it while using EpicSpawners Plugin. Admins have to manually /bsb limits calc to fix this issue.

**Steps to reproduce the behavior:**
1. Install EpicSpawners and BBox
2. Place spawners then check /is limits
3. Break it then check /is limits again
4. It's not updating.

**Expected behavior**
Only mob spawners didn't updated, but other blocks did.

**Screenshots**
Coming soon: I'm on phone

**Server Information:**
 - Java 11
 - Running PAPER 1.13.2 - #626
 - BentoBox version: 1.4.0
 - Loaded Addons:
 - Biomes 0.4.5
 - BSkyBlock 1.4.2
 - Challenges 0.6.5-SNAPSHOT-#145
 - Greenhouses 0.0.2-SNAPSHOT
 - Level 1.4.0
 - Limits 0.2.0-SNAPSHOT
 - WelcomeWarps 1.4.0

**Comment by tastybento** [comment]
Try this one, tell me if it works.
https://github.com/BentoBoxWorld/addon-limits/releases/tag/0.2.1

**Comment by variananora** [comment]
Sorry for the late reply. The notification didn't pushed to my email :/.
Anyway, It seems it's working now.
Thank you for fast update!
