### ISSUE TITLE
bug with permission based limit

### ISSUE THREAD

**Issue by OGreenC** [BentoBoxWorld/addon-limits#21]
**Description**
It seems like limits merge at some point, meaning some limits inherits limits from other items.
It's hard to explain, and I'm not sure just why and when this happens, but I'm able reproduce the bug, on a test server, with the following setup:

**Steps to reproduce the behavior:**
1. Give the player the following permissions (I'm using luckperms):
bskyblock.island.limit.hopper.100
bskyblock.island.limit.piston.101
bskyblock.island.limit.beacon.102
bskyblock.island.limit.spawner.103
2. Relog
3. Open island limits w. /island limits, and see that multiple items have the limit "103" - thats at least what happens for me.

**Expected behavior**
I would expect the hopper limit to be 100, piston 101 and so on.

**Screenshots**
Here's a picture of my permissions:
https://gyazo.com/3ce3e44869563405068b982906f578d8

Here's a picture of my /island limits menu (after I've relogged, ofc)
The limit for pistons should idealy be 101. (according to the perm)
https://gyazo.com/ad28ebd86e0320d76bd7f65e9950e65c

**Server Information:**
As before mentioned, I'm currently running BentoBox on a test server, thus it is a localhost server.

- Database: YAML
- OS: Windows 10
- Java version: 1.8.0_151
 - BentoBox version: 1.4.0
 - Addons installed? 
   BSkyblock 1.4.2
   Limits 0.2.1-SNAPSHOT

 - Other plugins? [Do '/plugins' and copy/paste from the console]
Bentobox, Essentials, LuckPerms, Multiverse-Core*, Vault*

**Comment by tastybento** [comment]
Thanks, I'll look into this. By the way, please test on the latest release of BentoBox 1.5.1 and BSkyBlock 1.5.0. Also Limits does not run on YAML database, only JSON, but you can switch to JSON from YAML using the YAML2JSON database setting in BentoBox's config.yml on 1.5.1.

**Comment by OGreenC** [comment]
Ah! - I didn't know, that the current version of limits, was compatible with bentobox 1.5.x.

I've now updated BentoBox and BSkyblock to said version, but unfortunately, that diden't solve the problem. I've also updated the Database, as you mentioned.

We're using MySQL on our live server, so it wouldn't have been a problem either way.

I'll be happy to do more testing to get closer to solving the problem, if necessary - just hit me up!

**Comment by tastybento** [comment]
Okay. I’ll have a look at this tonight and see what’s going on.

**Comment by tastybento** [comment]
Confirmed. Now working on a fix.

**Comment by tastybento** [comment]
Okay, fixed it. Thanks!
