### ISSUE TITLE
Placed blocks deleted on server restart

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/addon-limits#6]
**Description**
When restarting the server, the blocks placed are reset (File inside )

**Steps to reproduce the behavior:**
1. Reach to a limit of a block
2. Restart the server
3. You can still place that block until reaching the limit again (at this time, the island file inside IslandBlockCount is reseted.)

Using Level 0.0.2

**Comment by tastybento** [comment]
What database?

**Comment by YellowZaki** [comment]
Flat file, yml.
