### ISSUE TITLE
Raw instalation of addon-limits get error after...

### ISSUE THREAD

**Issue by Helomi** [BentoBoxWorld/addon-limits#8]
**Description**
I didnt saw any problem with this error its just annoing :D
Error:
![obrazok](https://user-images.githubusercontent.com/16295223/52557893-18536e80-2df1-11e9-9eee-3c403b486b0b.png)

**Steps to reproduce the behavior:**
1 Install bentobox
2 Install addons (bskyblock, limits, welcomewarps, level)
3. Do /is and 2x /is restart 
4. Yey you got error

**Expected behavior**

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used YAML and MySQL
 - OS: Debian i think (linux)
 - Java Version: 8
 - BentoBox version: last one

**Additional context**

**Comment by tastybento** [comment]
I think this is an old version of the add-on.

**Comment by tastybento** [comment]
If this is not 0.1.0, recommend doing a fresh install with 0.1.0 release.
